### ISSUE TITLE
Travis CI fails in every Pull request 

### ISSUE THREAD

**Issue by isuruAb** [99xt/youtube-fullscreen-playlist#30]
Travis fails in every pull request even in the documentation  PRs

**Comment by dinukadesilva** [comment]
Currently, there is no a test script defined for `youtube-queuing-bot` and that why the Travis ci is always failing and this would have been fixed in https://github.com/99xt/youtube-queuing-bot/pull/20

**Comment by isuruAb** [comment]
@dinukadesilva  yes. mention this issue in you PR 👍

**Comment by rehrumesh** [comment]
@isuruAb as #20 is merged, i believe we can close this. WDYT?

**Comment by isuruAb** [comment]
@rehrumesh  still travis fails. i have updated .travis.yml file. @dinukadesilva  please check
